<?php


// http://localhost/moodle/mod/mathcode/ajax.php?payload=%22eyJkYXRhY29kZSI6IkxPR19DbGlja1NheSIsImlkIjoyLCJ0ZXh0Ym9vayI6ImphdmFzY3JpcHQiLCJkYXRhMDEiOiJUaGUgbW9zdCBmYW1vdXMgdGV4dGJvb2sgb2YgYWxsIHRpbWUgaXMgIiwidW5pcSI6IkExQ1YifQ==%22
// need lots of checking here first


ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);


$query = "payload=eyJkYXRhY29kZSI6IkxPR19SdW5Db2RlIiwiaWQiOiIxIiwidGV4dGJvb2siOiJwbGF5Z3JvdW5kIiwiZGF0YTAxIjoiIiwiZGF0YTAyIjoiU1ZPUFdUSDI2IiwiZGF0YTA1IjoiTHk4Z1ptOXlJR2x1Wm05eWJXRjBhVzl1SUdGaWIzVjBJSFJvYVhNZ1pXUnBkRzl5SUhacGMybDBJR2gwZEhCek9pOHZiV2xqY205emIyWjBMbWRwZEdoMVlpNXBieTl0YjI1aFkyOHRaV1JwZEc5eUx3cFVVMWd1Y0c5cGJuUW9XekFzTUYwcENsUlRXQzVwYldGblpTZ2lhV052Ym5NdllXeHBaVzR0TlM1d2JtY2lMRnN3TERCZEtRPT0iLCJkYXRhMDYiOiJhVzF3YjNKMElIc2dWRmhISUgwZ1puSnZiU0FpTGk5a2FYTjBMM1J6ZUdkeVlYQm9MbXB6SWpzZ0lHeGxkQ0JVVTFnZ1BTQlVXRWN1VkZOWVIzSmhjR2d1YVc1cGRFSnZZWEprS0NKcWVHZGliM2dpS1RzPSIsImRhdGEwNyI6IlpHVmpiR0Z5WlNCc1pYUWdWRk5ZT2lCVVdFY3VWRk5ZUW05aGNtUTciLCJwYXJhZ3JhcGgiOiIifQ==:";
require_once('models.php');   // looks like mathcode version
writeRecord($query);
