export declare type V2 = [number, number];
export declare type V3 = [number, number, number];
export declare type V4 = [number, number, number, number];
export declare function dot(a: V2, b: V2): number;
export declare function dot(a: V3, b: V3): number;
export declare function dot(a: V4, b: V4): number;
export declare function normLength(a: V3): number;
export declare function normalize(a: V2): V2;
export declare function normalize(a: V3): V3;
export declare function normalize(a: V4): V4;
export declare function scalarmult(a: V2, b: number): V2;
export declare function scalarmult(a: V3, b: number): V3;
export declare function scalarmult(a: V4, b: number): V4;
export declare function cross(lhs: V3, rhs: V3): V3;
export declare function plus(a: V2, b: V2): V2;
export declare function plus(a: V3, b: V3): V3;
export declare function plus(a: V4, b: V4): V4;
export declare function minus(a: V2, b: V2): V2;
export declare function minus(a: V3, b: V3): V3;
export declare function minus(a: V4, b: V4): V4;
